schema_version = "1.0.0"
id = "spritesheet_frame_selector"
version = "0.1.0"
name = "SpriteSheet Frame Selector"
tagline = "Select animation frames visually for spritesheet export"
maintainer = "Amaruc"
type = "add-on"
blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["Animation", "Import-Export"]
